wavsep:
  image: nsunina/wavsep-enhancement:v0.1-alpha
  container_name: wavsep
  ports:
    - "127.0.0.1:8080:8080"
  links:
    - wavsepdb

wavsepdb:
  image: mysql:5.7.37
  container_name: wavsepdb
  ports:
    - "127.0.0.1:3306:3306"
  command: mysqld --default-authentication-plugin=mysql_native_password
  environment:
    MYSQL_ROOT_PASSWORD: 'pass'
    MYSQL_ROOT_HOST: '%'



