wavsep:
  image: wavsep
  container_name: wavsep
  ports:
    - '8080:8080'
  links:
    - wavsepdb

wavsepdb:
  image: mysql:5.7.37
  container_name: wavsepdb
  ports:
    - '3306:3306'
  command: mysqld --default-authentication-plugin=mysql_native_password
  environment:
    MYSQL_ROOT_PASSWORD: 'pass'
    MYSQL_ROOT_HOST: '%'



